### ISSUE TITLE
Upload interrupted?

### ISSUE THREAD

**Issue by GeroBH** [MaslowCommunityGarden/Website#40]
https://forums.maslowcnc.com/t/cant-add-a-project-to-the-community-garden/8592/5
Most of the reports of uploading errors, i tried and succeed with:
- a .zip file with a .dxf and a picture named mainpicture.jpg.
- was logged into git

Tonight neither own managed, nor community worked.

What's up?

**Comment by BarbourSmith** [comment]
I am seeing the same issue:

![image](https://user-images.githubusercontent.com/9359447/51780553-5e9aa380-214a-11e9-954c-06e3183bf837.png)


I can't do it today, but I will jump in first thing tomorrow and figure out what is going on

**Comment by BarbourSmith** [comment]
I believe that this is now fixed and I am working on a rebuilt from scratch replacement for the community garden. 

Do we feel ready to close this issue?

**Comment by GeroBH** [comment]
Nope. The script was unable to write your inputs to the file - pulled from github
At least on my side the test failed with the same result.
[lift-desk.zip](https://github.com/MaslowCommunityGarden/Website/files/2823125/lift-desk.zip)
mainpicture.jpg
![mainpicture](https://user-images.githubusercontent.com/25812652/52145870-46a7b000-2673-11e9-89ea-269627409336.jpg)

**Comment by BarbourSmith** [comment]
Darn. 

I am seeing the same thing. 

Restarting the server seems to fix the issue, but apparently it doesn't solve the problem forever. 


It should be working now, will you give it another test?

![image](https://user-images.githubusercontent.com/9359447/52161365-14439480-26ff-11e9-9010-24d1aae19dd0.png)


![image](https://user-images.githubusercontent.com/9359447/52161359-042bb500-26ff-11e9-896b-464e7bfc9dd7.png)

**Comment by GeroBH** [comment]
Due that I will not see if it worked, https://forums.maslowcnc.com/t/community-garden-missing-js/8673
I will wait with the test ;-)

**Comment by BarbourSmith** [comment]
It's like it knows I am working on a replacement and so it is demanding attention 😢

**Comment by GeroBH** [comment]
Ok, the second test worked! So the script detects the word 'test' and prevents the upload if that word is found?

**Comment by BarbourSmith** [comment]
Wow you are fast!! I came here to let you know I thought it was working and you've already tested it! Amazing! 

I guess we're closer in time zones now 😁 

Yes, you got it. I felt bad spamming the forums every time I did a test so if you have the word test in the name of the project it won't make a github repo or post in the forums 👍 👍

**Comment by GeroBH** [comment]
The Forum post was not created, is that because i choose 'self managed'?
Just now it showed up :-) To fast today.

**Comment by BarbourSmith** [comment]
The forum post should be creates the first time someone clicks on the
"forums" tab of the page. It usually happens pretty quickly, but it can
take a while sometimes.
